# Global configuration of pipeline
global:
  save_path: ./output

# Simplified Configuration for LLM compression
model:
  name: Qwen
  model_path: Qwen/Qwen3-30B-A3B
  trust_remote_code: true
  low_cpu_mem_usage: true
  use_cache: false
  torch_dtype: float32
  device_map: auto

# Compression configuration
compression:
  name: PTQ
  quantization:
    name: fp8_static
    bits: 8
    quant_method:
      weight: "per-tensor"
      activation: "per-tensor"
    ignore_layers:         # Skip quantization for these layers
      - "lm_head"

# Transform configuration for SpinQuant
transform:
  name: SpinQuant
  spin_config:
    had_dim: -1
    rotation_mode: Hadamard   # "Hadamard" or "Random"
    ignore_layers: []
  output_log: false

# Dataset for calibration
# Dataset for calibration
dataset:
  name: TextDataset
  data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
  max_seq_length: 2048
  num_samples: 256
  batch_size: 1